# -*- coding: utf-8 -*-
"""ocr for sdgp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBLlXN5UFz7MyUwARZzlKdRBuUavJrRY
"""

# 1. Remove current Pillow
!pip uninstall -y pillow

# 2. Install compatible version
!pip install pillow==10.3.0 --no-cache-dir --quiet

!pip install -q --upgrade \
    easyocr \
    google-generativeai \

import easyocr
import google.generativeai as genai
import re
from google.colab import files

GEMINI_API_KEY = "AIzaSyAkYXZEG7nk_Tyy8oMGCRSOPezdlDm97HE"  # ← Change this to your own key

GEMINI_MODEL = "gemini-1.5-flash"  # alternatives: "gemini-1.5-flash-001", "gemini-1.0-pro"

try:
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel(GEMINI_MODEL)
    print(f"Gemini initialized (model: {GEMINI_MODEL})")
except Exception as e:
    print("Gemini setup failed:", str(e))
    print("Try changing GEMINI_MODEL to one of:")
    print(" - gemini-1.5-flash-001")
    print(" - gemini-1.0-pro")
    print(" - gemini-pro")

def extract_text_easyocr(image_path):
    """Extract text using EasyOCR with paragraph grouping"""
    print("Running EasyOCR...")
    try:
        reader = easyocr.Reader(['en'], gpu=False, verbose=False)
        result = reader.readtext(image_path, detail=0, paragraph=True)
        text = "\n".join(result)
        text = re.sub(r'\s+', ' ', text).strip()
        return text
    except Exception as e:
        print("EasyOCR error:", str(e))
        return ""

def clean_ocr_text(text: str) -> str:
    """Fix common OCR mistakes in handwritten prescriptions"""
    if not text:
        return text

    replacements = {
        'Ta6s': 'Tabs', 'Tals': 'Tabs', 'Tak;': 'Tabs', 'Tako': 'Tabs',
        'tab': 'Tabs', 'tabl': 'Tabs', 'tablet': 'Tabs',
        'milliglam': 'milligram', 'milliqiam': 'milligram',
        'miligram': 'milligram', 'S0milhzmn': 'milligram',
        'miiiigiam': 'milligram', 'mgm': 'mg', 'm9': 'mg',
        'mowth': 'mouth', 'meeirh': 'mouth', 'motizh': 'mouth',
        'mctth': 'mouth', 'mewrh': 'mouth', 'mewth': 'mouth',
        'momnin': 'morning', '@omomin': 'morning', "'mownin": 'morning',
        'moming': 'morning', 'monin': 'morning',
        'dailj': 'daily', 'daij': 'daily', 'daly': 'daily',
        'on6': 'one', '4': 'by',
        'Gix': 'six', '6i': 'six', '632': '6', 'X5': '6',
        'tir': 'times', 'umes': 'times',
        'Wood': 'blood', 'Uood': 'blood', 'llood': 'blood', 'Iod': 'blood',
        'ueessevee': 'pressure', 'pveaoewe': 'pressure', 'peessevee': 'pressure',
        'conzeo': 'control', 'conzevl': 'control', 'oonzrvt': 'control',
        'koe': 'for', '= J': 'for', 'J for': 'for', "'loe": 'for',
        'Losaxan': 'Losartan', 'Losnian': 'Losartan', 'Loanian': 'Losartan',
        'Losnuan': 'Losartan', 'Iosnian': 'Losartan',
        'Disuense': 'Dispense', 'Dispenae': 'Dispense', 'Depns': 'Dispense',
        'Refiii': 'Refill', 'Refiu': 'Refill', 'Refi': 'Refill',
        'Slnature': 'Signature', 'Slgnature': 'Signature', '51gnature': 'Signature',
        'Substituton': 'Substitution', 'Suiystitution': 'Substitution',
    }

    for wrong, correct in replacements.items():
        text = text.replace(wrong, correct)

    text = re.sub(r'[^a-zA-Z0-9\s:;,.#/-]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def extract_prescriber_details(ocr_text: str):
    """Extract prescriber/facility info using Gemini API"""
    prompt = f"""You are an expert at reading medical prescriptions from OCR text.
Extract **only** prescriber and facility related information.

Return **strictly** valid JSON — nothing else:

{{
  "doctor_name": "full name or null",
  "specialization": "mentioned specialty or null",
  "registration_number": "DEA / license / council number or null",
  "facility_name": "clinic / hospital / practice name or null",
  "location": "full address / city / state / zip or null",
  "prescription_date": "date in any readable format or null"
}}

Cleaned OCR text:
{ocr_text}
"""

    try:
        response = model.generate_content(prompt)
        result_text = response.text.strip()

        if result_text.startswith("```"):
            result_text = result_text.split("```")[1].strip()
            if result_text.startswith("json"):
                result_text = result_text[4:].strip()

        print("\n" + "═"*70)
        print("PRESCRIBER / FACILITY DETAILS")
        print("═"*70)
        print(result_text)
        print("═"*70 + "\n")

    except Exception as e:
        print("Gemini API call failed:", str(e))

print("=== Upload your prescription image (jpg / png) ===\n")

uploaded = files.upload()

if uploaded:
    image_path = list(uploaded.keys())[0]
    print(f"\nProcessing: {image_path}\n")

    raw_text = extract_text_easyocr(image_path)
    print("RAW OCR OUTPUT:")
    print("-"*80)
    print(raw_text or "(no text detected)")
    print("-"*80 + "\n")

    if raw_text.strip():
        cleaned_text = clean_ocr_text(raw_text)
        print("CLEANED TEXT:")
        print("-"*80)
        print(cleaned_text)
        print("-"*80 + "\n")

        print("Extracting structured information...")
        extract_prescriber_details(cleaned_text)
else:
    print("No image uploaded.")